version: '3.4'

services:
  identityserver.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=User ID=postgres;Password=Password*-1;Host=identityserver.db;Port=5432;Database=IdentityServerDb;
    ports:
      - "5100:80"
    depends_on:
      - identityserver.db
  identityserver.db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=IdentityServerDb
      - POSTGRES_PASSWORD=Password*-1
    ports:
      - 5432:5432
    volumes:
      - identityserverdb_volume:/var/lib/postgresql/data
