version: '3.4'

services:
  identityserver.api:
    container_name: identityserver-api
    image: mertguney/identityserverapi:${version}
    build:
      context: .
      dockerfile: src/Presentation/IdentityServer.Api/Dockerfile
  identityserver.db:
    container_name: identityserver-db
    image: postgres

volumes:
  identityserverdb_volume: